# Generated by Django 4.0.5 on 2022-07-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0002_password_manager_delete_myusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password_manager',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='password_manager',
            name='user',
        ),
    ]
